// <auto-generated />
using System;
using IA_RoboBerto.Repositorio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IA_RoboBerto.Migrations
{
    [DbContext(typeof(RoboBertoContext))]
    partial class RoboBertoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IA_RoboBerto.Modelos.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cat_codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cat_nome");

                    b.HasKey("Id");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cha_codigo");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cha_aberto_em");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cha_resolvido_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cha_descricao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("cha_prioridade");

                    b.Property<DateTime>("SlaVenceEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cha_sla_vence_em");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("cha_status");

                    b.Property<string>("SugestaoGemini")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cha_sugestao");

                    b.Property<bool?>("SugestaoResolveu")
                        .HasColumnType("boolean")
                        .HasColumnName("cha_resolvido_com_ia");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cha_titulo");

                    b.Property<Guid>("cat_codigo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("cha_usuario_autor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("cha_usuario_tecnico")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("cat_codigo");

                    b.HasIndex("cha_usuario_autor");

                    b.HasIndex("cha_usuario_tecnico");

                    b.ToTable("chamado", (string)null);
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dep_codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dep_nome");

                    b.HasKey("Id");

                    b.ToTable("departamento", (string)null);
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("men_codigo");

                    b.Property<DateTime>("DataHoraMensagem")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("men_data_hora_texto");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("men_texto");

                    b.Property<Guid?>("cha_codigo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("usu_codigo")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("cha_codigo");

                    b.HasIndex("usu_codigo");

                    b.ToTable("mensagem", (string)null);
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usu_codigo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_datacriacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usu_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usu_nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usu_senha_hash");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usu_telefone");

                    b.Property<Guid>("dep_codigo")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("dep_codigo");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("role_usuario", b =>
                {
                    b.Property<Guid>("usu_codigo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("role_codigo")
                        .HasColumnType("uuid");

                    b.HasKey("usu_codigo", "role_codigo");

                    b.HasIndex("role_codigo");

                    b.ToTable("role_usuario");
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Chamado", b =>
                {
                    b.HasOne("IA_RoboBerto.Modelos.Categoria", "Categoria")
                        .WithMany("Chamados")
                        .HasForeignKey("cat_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IA_RoboBerto.Modelos.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("cha_usuario_autor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IA_RoboBerto.Modelos.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("cha_usuario_tecnico")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Mensagem", b =>
                {
                    b.HasOne("IA_RoboBerto.Modelos.Chamado", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("cha_codigo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IA_RoboBerto.Modelos.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("usu_codigo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Usuario", b =>
                {
                    b.HasOne("IA_RoboBerto.Modelos.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("dep_codigo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("role_usuario", b =>
                {
                    b.HasOne("IA_RoboBerto.Modelos.Role", null)
                        .WithMany()
                        .HasForeignKey("role_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_role_usuario_role");

                    b.HasOne("IA_RoboBerto.Modelos.Usuario", null)
                        .WithMany()
                        .HasForeignKey("usu_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_role_usuario_usuario");
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Categoria", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Chamado", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("IA_RoboBerto.Modelos.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
